# Generated by Django 5.1.2 on 2025-03-13 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotserver', '0005_alter_food_options_table_isbooked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='number',
            new_name='table_name',
        ),
    ]
