# Generated by Django 5.1.2 on 2025-03-14 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotserver', '0007_order_date_order_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='table_number',
            new_name='table',
        ),
    ]
