# Generated by Django 5.1.2 on 2025-03-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotserver', '0008_rename_table_number_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
