# Generated by Django 5.1.2 on 2025-03-14 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotserver', '0009_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ref_number',
        ),
    ]
