# Generated by Django 5.1.2 on 2025-03-12 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotserver', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='name',
            new_name='food_name',
        ),
    ]
