# Generated by Django 5.1.2 on 2025-03-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotserver', '0004_rename_name_food_food_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['food_name']},
        ),
        migrations.AddField(
            model_name='table',
            name='isBooked',
            field=models.BooleanField(default=False),
        ),
    ]
